draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30
  inner_pad_w: 2
  inner_pad_h: 2
  outer_pad_w: 30
  outer_pad_h: 60
  n_columns: 1
  dark_mode: false
  separate_combo_diagrams: false

parse_config:
  zmk_combos:
    caps_lock_combo:
      dendron: true
      align: bottom
      offset: 0.25
  raw_binding_map:
    "&sys_reset": RST
    "&bootloader": BOOT
  zmk_keycode_map:
    N1: {t: "1", s: "!"}
    N2: {t: "2", s: "@"}
    N3: {t: "3", s: "#"}
    N4: {t: "4", s: "$"}
    N5: {t: "5", s: "%"}
    N6: {t: "6", s: "^"}
    N7: {t: "7", s: "&"}
    N8: {t: "8", s: "*"}
    N9: {t: "9", s: "("}
    N0: {t: "0", s: ")"}
    GRAVE: {t: "`", s: "~"}
    BACKSLASH: {t: "\\", s: "|"}
    MINUS: {t: "-", s: "_"}
    EQUAL: {t: "=", s: "+"}
    LBKT: {t: "[", s: "{"}
    RBKT: {t: "]", s: "}"}
    SEMICOLON: {t: ";", s: ":"}
    APOSTROPHE: {t: "'", s: "\""}
    COMMA: {t: ",", s: "<"}
    DOT: {t: ".", s: ">"}
    SLASH: {t: "/", s: "?"}
    INSERT: INS
    PRINTSCREEN: PRTSC
    SCROLLLOCK: SCRLK
    PAUSE_BREAK: BRK
    PAGE_DOWN: PGDN
    PAGE_UP: PGUP
    LSHIFT: SFT
    RSHIFT: SFT
    DELETE: DEL
